# Generated by Django 4.1.4 on 2023-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.TextField(verbose_name='Название группы')),
                ('idUser', models.TextField(verbose_name='ID аккаунта Телеграм')),
                ('nameUser', models.TextField(verbose_name='Имя пользователя')),
                ('alertStatus', models.TextField(verbose_name='Статус оповещений')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
